### PR TITLE
Fix home tab fetching

### LINKED ISSUE #183: "Everything" view doesn't work when there are three or more instances
### Device info

- OS: Android 8.1.0, this issue also happens on Linux
- Device: LG Nexus 5X

### Describe the bug
When being logged in to two accounts (three counting the unremovable lemmy.ml) the main home view doesn't work. I can see each individual instance, but not the Everything view

### Steps to reproduce

1. Log in to two accounts
2. Click on the home icon in bottom left
3. Choose any option under "Everything" in the dropdown on the top
4. See an endless spinner

### Expected behavior
I expect to see entries from every instance

### Screenshots/Screencasts
https://video.kuba-orlik.name/videos/watch/1288df41-180a-4f93-a15c-f8eca519edef

### PR DESCRIPTION
**Pull request by shilangyu**

### CODE REVIEW

File: lib/pages/home_tab.dart [hunk 1]
```diff
@@ -277,32 +277,31 @@ class InfiniteHomeList extends HookWidget {
           listingType != PostListingType.community, 'only subscribed or all');
 
       final instances = () {
-        if (listingType == PostListingType.all) {
-          return accStore.instances;
-        } else {
+        if (listingType == PostListingType.subscribed) {
```
Comment (shilangyu) [inline lib/pages/home_tab.dart:280]: @krawieck Was there a reason why the `if` was the other way around? I think we want `loggedInInstances` only when Subscribed is selected, no?

File: lib/pages/home_tab.dart [hunk 2]
```diff
@@ -277,32 +277,31 @@ class InfiniteHomeList extends HookWidget {
...
+            limit: limit,
+            auth: accStore.defaultTokenFor(instanceHost)?.raw,
+          ))
+      ];
+      final instancePosts = await Future.wait(futures);
+      final longest = instancePosts.map((e) => e.length).reduce(max);
 
-      for (var i = 0; i < longest; i++) {
-        for (final el in posts) {
-          if (el.elementAt(i) != null) {
```
Comment (shilangyu) [inline lib/pages/home_tab.dart:301]: Sadly `.elementAt` also throws, so a null check won't work

File: lib/pages/home_tab.dart (hunk 1 above)
Comment (krawieck) [reply lib/pages/home_tab.dart:280]: it was that way cuz there were only 2 possible values that listingType can have, so it didn't really matter

**Review by krawieck — APPROVED** [review]
